###配置中心的端口号
server:
  port: 8888
###服务别名（服务注册到注册中心的名字）注意：别名千万不能包含下划线，不然服务调用时，使用别名会报错找不到url
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          ###Git的地址
          uri: https://gitee.com/liqiye1/springcloud_Config.git
          ###Git项目里面的文件夹名
          search-paths:
          - config
          ###如果这个Git项目设置了私有,必须要填写用户名密码（你这个Git仓库对应的用户名密码）
          #username: 1159140456@qq.com
          #password: 13556975841Lqy
      ###分支名
      label: master
eureka:
  client:
    service-url:
      ###当前配置中心服务注册到的指定注册中心rureka（如果是集群的注册中心，用逗号分隔开）
      defaultZone: http://localhost:8761/eureka/,http://localhost:9761/eureka/
    ###需要将我的服务注册到rureka上
    register-with-eureka: true
    ###需要检索服务
    fetch-registry: true
